// Generates WebP grid thumbnails + a data manifest for the testimonials gallery.
// Run: npm run thumbs
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const DIR = path.resolve('public/assets/testimonials');
const THUMBS = path.join(DIR, 'thumbs');
fs.mkdirSync(THUMBS, { recursive: true });

const files = fs.readdirSync(DIR)
  .filter(f => /^testimonial-\d+\.jpe?g$/i.test(f))
  .sort();

const manifest = [];
for (const file of files) {
  const src = path.join(DIR, file);
  const base = file.replace(/\.jpe?g$/i, '');
  const meta = await sharp(src).metadata();
  const thumbName = `${base}.webp`;
  await sharp(src)
    .resize({ width: 420, withoutEnlargement: true })
    .webp({ quality: 72 })
    .toFile(path.join(THUMBS, thumbName));
  manifest.push({
    full: `/assets/testimonials/${file}`,
    thumb: `/assets/testimonials/thumbs/${thumbName}`,
    w: meta.width,
    h: meta.height,
  });
}

fs.writeFileSync(
  path.resolve('src/testimonials.data.js'),
  `// AUTO-GENERATED by scripts/gen-thumbs.mjs — do not edit by hand.\nexport default ${JSON.stringify(manifest, null, 2)};\n`
);
console.log(`Generated ${manifest.length} thumbnails + src/testimonials.data.js`);
