// AUTO-GENERATED by scripts/gen-thumbs.mjs — do not edit by hand.
export default [
  {
    "full": "/assets/testimonials/testimonial-01.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-01.webp",
    "w": 828,
    "h": 1043
  },
  {
    "full": "/assets/testimonials/testimonial-02.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-02.webp",
    "w": 828,
    "h": 748
  },
  {
    "full": "/assets/testimonials/testimonial-03.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-03.webp",
    "w": 828,
    "h": 735
  },
  {
    "full": "/assets/testimonials/testimonial-04.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-04.webp",
    "w": 828,
    "h": 1138
  },
  {
    "full": "/assets/testimonials/testimonial-05.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-05.webp",
    "w": 828,
    "h": 1043
  },
  {
    "full": "/assets/testimonials/testimonial-06.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-06.webp",
    "w": 828,
    "h": 714
  },
  {
    "full": "/assets/testimonials/testimonial-07.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-07.webp",
    "w": 828,
    "h": 748
  },
  {
    "full": "/assets/testimonials/testimonial-08.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-08.webp",
    "w": 828,
    "h": 735
  },
  {
    "full": "/assets/testimonials/testimonial-09.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-09.webp",
    "w": 828,
    "h": 1138
  },
  {
    "full": "/assets/testimonials/testimonial-10.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-10.webp",
    "w": 828,
    "h": 933
  },
  {
    "full": "/assets/testimonials/testimonial-11.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-11.webp",
    "w": 828,
    "h": 875
  },
  {
    "full": "/assets/testimonials/testimonial-12.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-12.webp",
    "w": 828,
    "h": 1251
  },
  {
    "full": "/assets/testimonials/testimonial-13.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-13.webp",
    "w": 828,
    "h": 940
  },
  {
    "full": "/assets/testimonials/testimonial-14.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-14.webp",
    "w": 828,
    "h": 551
  },
  {
    "full": "/assets/testimonials/testimonial-15.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-15.webp",
    "w": 828,
    "h": 1129
  },
  {
    "full": "/assets/testimonials/testimonial-16.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-16.webp",
    "w": 828,
    "h": 1235
  },
  {
    "full": "/assets/testimonials/testimonial-17.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-17.webp",
    "w": 828,
    "h": 1114
  },
  {
    "full": "/assets/testimonials/testimonial-18.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-18.webp",
    "w": 828,
    "h": 1210
  },
  {
    "full": "/assets/testimonials/testimonial-19.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-19.webp",
    "w": 828,
    "h": 1070
  },
  {
    "full": "/assets/testimonials/testimonial-20.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-20.webp",
    "w": 828,
    "h": 351
  },
  {
    "full": "/assets/testimonials/testimonial-21.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-21.webp",
    "w": 828,
    "h": 490
  },
  {
    "full": "/assets/testimonials/testimonial-22.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-22.webp",
    "w": 828,
    "h": 1043
  },
  {
    "full": "/assets/testimonials/testimonial-23.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-23.webp",
    "w": 828,
    "h": 539
  },
  {
    "full": "/assets/testimonials/testimonial-24.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-24.webp",
    "w": 828,
    "h": 646
  },
  {
    "full": "/assets/testimonials/testimonial-25.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-25.webp",
    "w": 828,
    "h": 592
  },
  {
    "full": "/assets/testimonials/testimonial-26.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-26.webp",
    "w": 795,
    "h": 1280
  },
  {
    "full": "/assets/testimonials/testimonial-27.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-27.webp",
    "w": 828,
    "h": 830
  },
  {
    "full": "/assets/testimonials/testimonial-28.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-28.webp",
    "w": 828,
    "h": 809
  },
  {
    "full": "/assets/testimonials/testimonial-29.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-29.webp",
    "w": 828,
    "h": 457
  },
  {
    "full": "/assets/testimonials/testimonial-30.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-30.webp",
    "w": 828,
    "h": 556
  },
  {
    "full": "/assets/testimonials/testimonial-31.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-31.webp",
    "w": 828,
    "h": 1252
  },
  {
    "full": "/assets/testimonials/testimonial-32.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-32.webp",
    "w": 828,
    "h": 824
  },
  {
    "full": "/assets/testimonials/testimonial-33.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-33.webp",
    "w": 828,
    "h": 929
  },
  {
    "full": "/assets/testimonials/testimonial-34.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-34.webp",
    "w": 828,
    "h": 720
  },
  {
    "full": "/assets/testimonials/testimonial-35.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-35.webp",
    "w": 828,
    "h": 985
  },
  {
    "full": "/assets/testimonials/testimonial-36.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-36.webp",
    "w": 828,
    "h": 899
  },
  {
    "full": "/assets/testimonials/testimonial-37.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-37.webp",
    "w": 828,
    "h": 413
  },
  {
    "full": "/assets/testimonials/testimonial-38.jpeg",
    "thumb": "/assets/testimonials/thumbs/testimonial-38.webp",
    "w": 828,
    "h": 404
  }
];
